#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' ''  '' '' '' '' '' '' 
		# bspc monitor ${monitor} -n "$name" -d '' '' '' '' '漣' '' '' ''

		let name++
	done
}
workspaces

bspc config border_width 2.35
bspc config window_gap 3
bspc config split_ratio 0.55

bspc config focused_border_color "#ea5455" ##1751FD"  #"#ff304f" #"#bf5caa" #"#f9ff21" "#ff304f" #"#21e6c1"     ##'#F76D01' #"#D15C5C" #"#42A5F5" 
bspc config normal_border_color "#4a697d"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

# 2 > code
declare -a code=(Geany code-oss Subl)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

# 3 > web
bspc rule -a firefox desktop='^3' follow=on focus=on
bspc rule -a chromium desktop='^3' follow=on focus=on
bspc rule -a brave desktop='^3' follow=on focus=on
bspc rule -a Google-chrome desktop='^3' follow=on focus=on  

# 4 > files
declare -a files=(Pcmanfm Thunar qBittorrent dolphin)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > Communication
declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 7 > media
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

# 8 > settings
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off


# special rules
###_____MY__PERSONAL__ADDED_CONFIG 
#bspc rule -a Code desktop='^8' state=pseudo_tiled center=true rectangle=1000x625+0+0
#bspc rule -a Code state=tiled center=false rectangle=1048x738+0+28
bspc rule -a Code desktop='^2' state=tiled center=false rectangle=1048x766+0+0
bspc rule -a easyeffects desktop='^8' state=tiled follow=on focus=on
bspc rule -a helvum desktop='^8' state=tiled follow=on focus=on
bspc rule -a Gnome-boxes desktop='^7' state=tiled follow=on focus=on

#####
# bspc rule -a alacritty-float state=floating follow=on focus=on
# bspc rule -a Pcmanfm state=floating follow=on focus=on
# bspc rule -a Onboard state=floating follow=on focus=on
# bspc rule -a Audacious state=floating follow=on focus=on
# bspc rule -a Firefox:Places state=floating follow=on focus=on
# bspc rule -a Viewnior state=floating follow=on focus=on
# bspc rule -a Nm-connection-editor state=floating follow=on focus=on
# bspc rule -a Conky state=floating manage=off
# bspc rule -a stalonetray state=floating manage=off



## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Running Ulauncher
#ulauncher &
aw-qt & #activitywatch Autostart

# Polybar Run
$HOME/.config/polybar/launch.sh &

#RClone Auto Run TODO: YOU MUST INSTALL RCLONE BEFORE RUNNING THIS Rclone is CloudStorage Client
#rclone rcd --rc-web-gui &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
# bash $HOME/.fehbg
nitrogen --restore &

# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
# bspbar
bspcomp
bspdunst
# borderSet
bspfloat &

