-- require("dapui").setup()
-- require("dapui").open()
-- local dap = require('dap')
--
-- -- write config for dart
-- dap.adapters.dart = {
--     type = "executable",
--     -- As of this writing, this functionality is open for review in https://github.com/flutter/flutter/pull/91802
--     command = "flutter",
--     args = { "debug_adapter" }
--
--
--
-- }
-- dap.configurations.dart = {
--     {
--         type = "dart",
--         request = "launch",
--         name = "Launch flutter",
--         dartSdkPath = os.getenv('HOME') .. "/flutter/bin/cache/dart-sdk/",
--         flutterSdkPath = os.getenv('HOME') .. "/flutter",
--         program = "${workspaceFolder}/lib/main.dart",
--         cwd = "${workspaceFolder}",
--     }
-- }
